/*
 * Copyright (C) 2006, 2007 Clam <ebordin@aapt.net.au>
 * 
 * This file is part of Lateral GM.
 * Lateral GM is free software and comes with ABSOLUTELY NO WARRANTY.
 * See LICENSE for details.
 */

package org.lateralgm.resources.sub;

import org.lateralgm.components.EventKeyInput;
import org.lateralgm.main.LGM;
import org.lateralgm.messages.Messages;
import org.lateralgm.resources.GmObject;
import org.lateralgm.resources.ResId;

public class Event extends ActionContainer
	{
	// mouse event types
	public static final byte EV_LEFT_BUTTON = 0;
	public static final byte EV_RIGHT_BUTTON = 1;
	public static final byte EV_MIDDLE_BUTTON = 2;
	public static final byte EV_NO_BUTTON = 3;
	public static final byte EV_LEFT_PRESS = 4;
	public static final byte EV_RIGHT_PRESS = 5;
	public static final byte EV_MIDDLE_PRESS = 6;
	public static final byte EV_LEFT_RELEASE = 7;
	public static final byte EV_RIGHT_RELEASE = 8;
	public static final byte EV_MIDDLE_RELEASE = 9;
	public static final byte EV_MOUSE_ENTER = 10;
	public static final byte EV_MOUSE_LEAVE = 11;
	public static final byte EV_MOUSE_WHEEL_UP = 60;
	public static final byte EV_MOUSE_WHEEL_DOWN = 61;
	public static final byte EV_GLOBAL_LEFT_BUTTON = 50;
	public static final byte EV_GLOBAL_RIGHT_BUTTON = 51;
	public static final byte EV_GLOBAL_MIDDLE_BUTTON = 52;
	public static final byte EV_GLOBAL_LEFT_PRESS = 53;
	public static final byte EV_GLOBAL_RIGHT_PRESS = 54;
	public static final byte EV_GLOBAL_MIDDLE_PRESS = 55;
	public static final byte EV_GLOBAL_LEFT_RELEASE = 56;
	public static final byte EV_GLOBAL_RIGHT_RELEASE = 57;
	public static final byte EV_GLOBAL_MIDDLE_RELEASE = 58;
	public static final byte EV_JOYSTICK1_LEFT = 16;
	public static final byte EV_JOYSTICK1_RIGHT = 17;
	public static final byte EV_JOYSTICK1_UP = 18;
	public static final byte EV_JOYSTICK1_DOWN = 19;
	public static final byte EV_JOYSTICK1_BUTTON1 = 21;
	public static final byte EV_JOYSTICK1_BUTTON2 = 22;
	public static final byte EV_JOYSTICK1_BUTTON3 = 23;
	public static final byte EV_JOYSTICK1_BUTTON4 = 24;
	public static final byte EV_JOYSTICK1_BUTTON5 = 25;
	public static final byte EV_JOYSTICK1_BUTTON6 = 26;
	public static final byte EV_JOYSTICK1_BUTTON7 = 27;
	public static final byte EV_JOYSTICK1_BUTTON8 = 28;
	public static final byte EV_JOYSTICK2_LEFT = 31;
	public static final byte EV_JOYSTICK2_RIGHT = 32;
	public static final byte EV_JOYSTICK2_UP = 33;
	public static final byte EV_JOYSTICK2_DOWN = 34;
	public static final byte EV_JOYSTICK2_BUTTON1 = 36;
	public static final byte EV_JOYSTICK2_BUTTON2 = 37;
	public static final byte EV_JOYSTICK2_BUTTON3 = 38;
	public static final byte EV_JOYSTICK2_BUTTON4 = 39;
	public static final byte EV_JOYSTICK2_BUTTON5 = 40;
	public static final byte EV_JOYSTICK2_BUTTON6 = 41;
	public static final byte EV_JOYSTICK2_BUTTON7 = 42;
	public static final byte EV_JOYSTICK2_BUTTON8 = 43;

	// other event types
	public static final byte EV_OUTSIDE = 0;
	public static final byte EV_BOUNDARY = 1;
	public static final byte EV_GAME_START = 2;
	public static final byte EV_GAME_END = 3;
	public static final byte EV_ROOM_START = 4;
	public static final byte EV_ROOM_END = 5;
	public static final byte EV_NO_MORE_LIVES = 6;
	public static final byte EV_NO_MORE_HEALTH = 9;
	public static final byte EV_ANIMATION_END = 7;
	public static final byte EV_END_OF_PATH = 8;
	public static final byte EV_USER0 = 10;
	public static final byte EV_USER1 = 11;
	public static final byte EV_USER2 = 12;
	public static final byte EV_USER3 = 13;
	public static final byte EV_USER4 = 14;
	public static final byte EV_USER5 = 15;
	public static final byte EV_USER6 = 16;
	public static final byte EV_USER7 = 17;
	public static final byte EV_USER8 = 18;
	public static final byte EV_USER9 = 19;
	public static final byte EV_USER10 = 20;
	public static final byte EV_USER11 = 21;
	public static final byte EV_USER12 = 22;
	public static final byte EV_USER13 = 23;
	public static final byte EV_USER14 = 24;
	public static final byte EV_USER15 = 25;

	// step event types
	public static final byte EV_STEP_NORMAL = 0;
	public static final byte EV_STEP_BEGIN = 1;
	public static final byte EV_STEP_END = 2;

	// XXX NOTE: java.awt.event.KeyEvent has constants appropriate for keyboard events

	/*
	 * Another note: The constant definitions were generated by a small GM program, which parses
	 * the clipboard (with parts of the gm manual on it) and generates the Java definitions.
	 */

	public int id = 0;
	public ResId other = null; // For collision Events
	public int mainId = 0;

	public String toString()
		{
		switch (mainId)
			{
			case MainEvent.EV_ALARM:
				return String.format(Messages.getString("Event.EVENT" + mainId + "_X"),id);
			case MainEvent.EV_COLLISION:
				GmObject obj = LGM.currentFile.gmObjects.get(other);
				String name;
				if (obj == null)
					name = "<undefined>";
				else
					name = obj.getName();
				return String.format(Messages.getString("Event.EVENT" + mainId + "_X"),name);
			case MainEvent.EV_KEYBOARD:
			case MainEvent.EV_KEYPRESS:
			case MainEvent.EV_KEYRELEASE:
				return String.format(Messages.getString("Event.EVENT" + mainId + "_X"),
						EventKeyInput.getGmKeyName(id));
			case MainEvent.EV_OTHER:
				if (id >= Event.EV_USER0)
					return String.format(Messages.getString("Event.Event" + mainId + "_X"),id
							- Event.EV_USER0);
				else
					return Messages.getString("Event.EVENT" + mainId + "_" + id);
			default:
				return Messages.getString("Event.EVENT" + mainId + "_" + id);
			}
		}
	}
